### ISSUE TITLE
Extend fc_neuron_type function

### ISSUE THREAD

**Issue by mmc46** [jefferis/flycircuit#41]
Could this function look up both annotation_class "NeuronType" (currently) and "ALGlomerulus"?

**Comment by jefferis** [comment]
There's an `fc_glom` function. Does that do what you want?

If you want to join the two up:

``
pngloms=fc_glom()
paste(fc_neuron_type(names(pngloms)), pngloms)
```

**Comment by mmc46** [comment]
fc_glom takes the neuron to return the glomerulus. I’d like to retrieve the neuron by searching with the glom.
I don’t think that’s possible at the moment.

**Comment by jefferis** [comment]
There is a helper function in the `fc_neuron_type` docs that could help.
```
fc_annotated_class("ALGlomerulus", regex='DM1')
```

**Comment by mmc46** [comment]
Yes, that works. Thanks.
